prod: false
addr: :8080
loglevel: trace
static: ./static
proxies:
  -
    proxy: www.dev1.com:8080
    host: http://localhost:8090
  -
    proxy: www.dev2.com:8080
    host: http://localhost:8091
ssl:
  redirecthttp:
    enable: true
    addr: :8080
  DisableLetsEncrypt: false
